"""Initial migration

Revision ID: ef88c499025b
Revises: 
Create Date: 2024-10-04 14:09:00.572903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef88c499025b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('example', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='intents_pkey')
    )
    # ### end Alembic commands ###
